Give a try to ManfredTremmel/gwt-bean-validators
https://github.com/ManfredTremmel/gwt-bean-validators

App Engine is not compatible with hibernate 5.2.x version!!

```
INFO] log4j:WARN Error during default initialization
[INFO] java.lang.NoClassDefFoundError: java.io.FileOutputStream is a restricted class. Please see the Google  App Engine developer's guide for more details.
[INFO] 	at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:52)
[INFO] 	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
[INFO] 	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
[INFO] 	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
[INFO] 	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
[INFO] 	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
[INFO] 	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
[INFO] 	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
[INFO] 	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
[INFO] 	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
[INFO] 	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
[INFO] 	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
[INFO] 	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
[INFO] 	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
[INFO] 	at java.lang.Class.forName0(Native Method)
[INFO] 	at java.lang.Class.forName(Class.java:348)
[INFO] 	at org.jboss.logging.LoggerProviders.tryLog4j(LoggerProviders.java:134)
[INFO] 	at org.jboss.logging.LoggerProviders.findProvider(LoggerProviders.java:96)
[INFO] 	at org.jboss.logging.LoggerProviders.find(LoggerProviders.java:34)
[INFO] 	at org.jboss.logging.LoggerProviders.<clinit>(LoggerProviders.java:31)
[INFO] 	at java.lang.Class.forName0(Native Method)
[INFO] 	at java.lang.Class.forName(Class.java:264)
[INFO] 	at com.google.appengine.tools.development.agent.runtime.RuntimeHelper.checkRestricted(RuntimeHelper.java:70)
[INFO] 	at com.google.appengine.tools.development.agent.runtime.Runtime.checkRestricted(Runtime.java:65)
[INFO] 	at org.jboss.logging.Logger.getLogger(Logger.java:2465)
[INFO] 	at org.jboss.logging.Logger$1.run(Logger.java:2565)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2529)
[INFO] 	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2516)
[INFO] 	at org.hibernate.validator.internal.util.logging.LoggerFactory.make(LoggerFactory.java:19)
[INFO] 	at org.hibernate.validator.internal.util.Version.<clinit>(Version.java:22)
[INFO] 	at org.hibernate.validator.internal.engine.ConfigurationImpl.<clinit>(ConfigurationImpl.java:69)
[INFO] 	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:31)
[INFO] 	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276)
[INFO] 	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:110)
[INFO] 	at com.project.server.GreetingServiceImpl.greetServer(GreetingServiceImpl.java:48)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:497)
[INFO] 	at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:130)
[INFO] 	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
[INFO] 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
[INFO] 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
[INFO] 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
[INFO] 	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
[INFO] 	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
[INFO] 	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
[INFO] 	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
[INFO] 	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
[INFO] 	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
[INFO] 	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
[INFO] 	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
[INFO] 	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:513)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
[INFO] 	at org.mortbay.jetty.Server.handle(Server.java:326)
[INFO] 	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
[INFO] 	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
[INFO] 	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
[INFO] 	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
[INFO] 	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
[INFO] 	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
[INFO] 	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
[INFO] 0    [638390632@qtp-1725008249-2] INFO  org.hibernate.validator.internal.util.Version  - HV000001: Hibernate Validator 5.2.4.Final
[INFO] 49   [638390632@qtp-1725008249-2] INFO  org.hibernate.validator.resourceloading.PlatformResourceBundleLocator  - Hibernate Validator cannot instantiate AggregateResourceBundle.CONTROL. This can happen most notably in a Google App Engine environment. A PlatformResourceBundleLocator without bundle aggregation was created. This only effects you in case you are using multiple ConstraintDefinitionContributor jars. ConstraintDefinitionContributors are a Hibernate Validator specific feature. All Bean Validation features work as expected. See also https://hibernate.atlassian.net/browse/HV-1023.
[INFO] Aug 17, 2016 7:04:55 PM com.google.appengine.tools.development.ApiProxyLocalImpl log
[INFO] SEVERE: javax.servlet.ServletContext log: Exception while dispatching incoming RPC call
[INFO] com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract com.project.shared.entities.GreetingResponse com.project.shared.GreetingService.greetServer(java.lang.String)' threw an unexpected exception: java.lang.NoClassDefFoundError: java.util.Optional is a restricted class. Please see the Google  App Engine developer's guide for more details.
[INFO] 	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
[INFO] 	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
[INFO] 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
[INFO] 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
[INFO] 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
[INFO] 	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
[INFO] 	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
[INFO] 	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
[INFO] 	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
[INFO] 	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
[INFO] 	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
[INFO] 	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
[INFO] 	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
[INFO] 	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:513)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
[INFO] 	at org.mortbay.jetty.Server.handle(Server.java:326)
[INFO] 	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
[INFO] 	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
[INFO] 	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
[INFO] 	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
[INFO] 	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
[INFO] 	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
[INFO] 	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
[INFO] Caused by: java.lang.NoClassDefFoundError: java.util.Optional is a restricted class. Please see the Google  App Engine developer's guide for more details.
[INFO] 	at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:52)
[INFO] 	at org.hibernate.validator.internal.metadata.provider.TypeAnnotationAwareMetaDataProvider.getTypeParameter(TypeAnnotationAwareMetaDataProvider.java:172)
[INFO] 	at org.hibernate.validator.internal.metadata.provider.TypeAnnotationAwareMetaDataProvider.findTypeArgumentsConstraints(TypeAnnotationAwareMetaDataProvider.java:96)
[INFO] 	at org.hibernate.validator.internal.metadata.provider.TypeAnnotationAwareMetaDataProvider.findTypeAnnotationConstraintsForMember(TypeAnnotationAwareMetaDataProvider.java:72)
[INFO] 	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findPropertyMetaData(AnnotationMetaDataProvider.java:244)
[INFO] 	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getFieldMetaData(AnnotationMetaDataProvider.java:227)
[INFO] 	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.retrieveBeanConfiguration(AnnotationMetaDataProvider.java:137)
[INFO] 	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getBeanConfiguration(AnnotationMetaDataProvider.java:125)
[INFO] 	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getBeanConfigurationForHierarchy(AnnotationMetaDataProvider.java:108)
[INFO] 	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.createBeanMetaData(BeanMetaDataManager.java:166)
[INFO] 	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.getOrCreateBeanMetaData(BeanMetaDataManager.java:194)
[INFO] 	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.isConstrained(BeanMetaDataManager.java:138)
[INFO] 	at org.hibernate.validator.internal.engine.ValidatorImpl.validateValue(ValidatorImpl.java:231)
[INFO] 	at com.project.server.GreetingServiceImpl.greetServer(GreetingServiceImpl.java:49)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:497)
[INFO] 	at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:130)
[INFO] 	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
[INFO] 	... 43 more
[INFO]
```